# Generated by Django 3.1.7 on 2021-03-09 04:41

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('issue_year', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Mechanics'), (2, 'Automatic'), (3, 'Robot')])),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
