# Generated by Django 3.1.7 on 2021-03-09 08:32

import apps.cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cars.models.upload_car_photo_path),
        ),
    ]
